In [80]:
!unzip '/content/drive/MyDrive/Dataset.zip'

Streaming output truncated to the last 5000 lines.
  inflating: Data/Happy/1087_IEO_HAP_LO.wav  
  inflating: Data/Happy/1087_IEO_HAP_MD.wav  
  inflating: Data/Happy/1087_IOM_HAP_XX.wav  
  inflating: Data/Happy/1087_ITH_HAP_XX.wav  
  inflating: Data/Happy/1087_ITS_HAP_XX.wav  
  inflating: Data/Happy/1087_IWL_HAP_XX.wav  
  inflating: Data/Happy/1087_IWW_HAP_XX.wav  
  inflating: Data/Happy/1087_MTI_HAP_XX.wav  
  inflating: Data/Happy/1087_TAI_HAP_XX.wav  
  inflating: Data/Happy/1087_TIE_HAP_XX.wav  
  inflating: Data/Happy/1087_TSI_HAP_XX.wav  
  inflating: Data/Happy/1087_WSI_HAP_XX.wav  
  inflating: Data/Happy/1088_DFA_HAP_XX.wav  
  inflating: Data/Happy/1088_IEO_HAP_HI.wav  
  inflating: Data/Happy/1088_IEO_HAP_LO.wav  
  inflating: Data/Happy/1088_IEO_HAP_MD.wav  
  inflating: Data/Happy/1088_IOM_HAP_XX.wav  
  inflating: Data/Happy/1088_ITH_HAP_XX.wav  
  inflating: Data/Happy/1088_ITS_HAP_XX.wav  
  inflating: Data/Happy/1088_IWL_HAP_XX.wav  
  inflating: Data/Happy/1088_

In [119]:
import os

file_path = ['/content/Data/Angry/desktop.ini', '/content/Data/Disgust/desktop.ini', '/content/Data/Fear/desktop.ini',
             '/content/Data/Happy/desktop.ini', '/content/Data/Neutral/desktop.ini', '/content/Data/Sad/desktop.ini',
             '/content/Data/Surprised/desktop.ini']  # Replace with the actual file path you want to remove

# Check if the file exists before attempting to remove it
for i in file_path:
  if os.path.exists(i):
    os.remove(i)
    print(f"File {i} has been removed.")
  else:
      print(f"File {i} does not exist.")


File /content/Data/Angry/desktop.ini does not exist.
File /content/Data/Disgust/desktop.ini has been removed.
File /content/Data/Fear/desktop.ini has been removed.
File /content/Data/Happy/desktop.ini has been removed.
File /content/Data/Neutral/desktop.ini has been removed.
File /content/Data/Sad/desktop.ini has been removed.
File /content/Data/Surprised/desktop.ini does not exist.


In [120]:
import os
import pandas as pd

In [121]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Angry'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Angry'
    paths.append(fpath)
    labels.append(label)

Angry = pd.DataFrame()
Angry['paths'] = paths
Angry['labels'] = labels


In [122]:
Angry.shape

(1923, 2)

In [123]:
Angry.head()

paths labels
0       /content/Data/Angry/1034_TSI_ANG_XX.wav  Angry
1       /content/Data/Angry/1073_MTI_ANG_XX.wav  Angry
2  /content/Data/Angry/03-01-05-02-02-02-04.wav  Angry
3       /content/Data/Angry/1013_IWW_ANG_XX.wav  Angry
4  /content/Data/Angry/03-01-05-01-01-01-19.wav  Angry

In [124]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Disgust'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Disgust'
    paths.append(fpath)
    labels.append(label)

Disgust = pd.DataFrame()
Disgust['paths'] = paths
Disgust['labels'] = labels


In [125]:
Disgust.shape

(1923, 2)

In [126]:
Disgust.head()

paths   labels
0   /content/Data/Disgust/1039_DFA_DIS_XX.wav  Disgust
1   /content/Data/Disgust/OAF_lot_disgust.wav  Disgust
2   /content/Data/Disgust/1048_WSI_DIS_XX.wav  Disgust
3  /content/Data/Disgust/YAF_calm_disgust.wav  Disgust
4   /content/Data/Disgust/1033_DFA_DIS_XX.wav  Disgust

In [127]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Fear'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Fear'
    paths.append(fpath)
    labels.append(label)

Fear = pd.DataFrame()
Fear['paths'] = paths
Fear['labels'] = labels


In [128]:
Fear.shape

(1923, 2)

In [129]:
Fear.head()

paths labels
0       /content/Data/Fear/1089_MTI_FEA_XX.wav   Fear
1       /content/Data/Fear/1090_IEO_FEA_MD.wav   Fear
2       /content/Data/Fear/1074_IEO_FEA_HI.wav   Fear
3       /content/Data/Fear/1090_WSI_FEA_XX.wav   Fear
4  /content/Data/Fear/03-01-06-02-01-01-10.wav   Fear

In [130]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Happy'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Happy'
    paths.append(fpath)
    labels.append(label)

Happy = pd.DataFrame()
Happy['paths'] = paths
Happy['labels'] = labels

In [131]:
Happy.shape

(1924, 2)

In [132]:
Happy.head()

paths labels
0  /content/Data/Happy/1040_IEO_HAP_MD.wav  Happy
1  /content/Data/Happy/1048_IEO_HAP_LO.wav  Happy
2  /content/Data/Happy/1049_IEO_HAP_LO.wav  Happy
3  /content/Data/Happy/1051_IEO_HAP_MD.wav  Happy
4  /content/Data/Happy/1004_IEO_HAP_LO.wav  Happy

In [133]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Neutral'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Neutral'
    paths.append(fpath)
    labels.append(label)

Neutral = pd.DataFrame()
Neutral['paths'] = paths
Neutral['labels'] = labels


In [134]:
Neutral.shape

(1895, 2)

In [135]:
Neutral.head()

paths   labels
0       /content/Data/Neutral/1007_TAI_NEU_XX.wav  Neutral
1     /content/Data/Neutral/YAF_third_neutral.wav  Neutral
2  /content/Data/Neutral/03-01-02-02-01-01-16.wav  Neutral
3       /content/Data/Neutral/1086_IOM_NEU_XX.wav  Neutral
4     /content/Data/Neutral/OAF_shirt_neutral.wav  Neutral

In [136]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Sad'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Sad'
    paths.append(fpath)
    labels.append(label)

Sad = pd.DataFrame()
Sad['paths'] = paths
Sad['labels'] = labels


In [137]:
Sad.shape

(1922, 2)

In [138]:
Sad.head()

paths labels
0  /content/Data/Sad/03-01-04-01-01-01-05.wav    Sad
1         /content/Data/Sad/YAF_merge_sad.wav    Sad
2          /content/Data/Sad/YAF_whip_sad.wav    Sad
3  /content/Data/Sad/03-01-04-02-01-01-18.wav    Sad
4          /content/Data/Sad/OAF_void_sad.wav    Sad

In [139]:
paths = []
labels = []


for root, dirs, files in os.walk('/content/Data/Surprised'):
  for filepath in files:
    fpath = os.path.join(root, filepath)
    label = 'Surprised'
    paths.append(fpath)
    labels.append(label)

Surprised = pd.DataFrame()
Surprised['paths'] = paths
Surprised['labels'] = labels


In [140]:
Surprised.shape

(652, 2)

In [141]:
Surprised.head()

paths     labels
0  /content/Data/Surprised/03-01-08-01-02-02-13.wav  Surprised
1  /content/Data/Surprised/03-01-08-01-01-01-11.wav  Surprised
2           /content/Data/Surprised/OAF_tool_ps.wav  Surprised
3           /content/Data/Surprised/OAF_fall_ps.wav  Surprised
4  /content/Data/Surprised/03-01-08-02-02-02-22.wav  Surprised

In [142]:
dataframes = [Angry, Disgust, Fear, Happy, Neutral, Sad, Surprised]
data = pd.concat(dataframes, ignore_index=True)

In [143]:
data.shape

(12162, 2)

In [144]:
data.head()

paths labels
0       /content/Data/Angry/1034_TSI_ANG_XX.wav  Angry
1       /content/Data/Angry/1073_MTI_ANG_XX.wav  Angry
2  /content/Data/Angry/03-01-05-02-02-02-04.wav  Angry
3       /content/Data/Angry/1013_IWW_ANG_XX.wav  Angry
4  /content/Data/Angry/03-01-05-01-01-01-19.wav  Angry

In [145]:
data['labels'].value_counts()

Happy        1924
Angry        1923
Disgust      1923
Fear         1923
Sad          1922
Neutral      1895
Surprised     652
Name: labels, dtype: int64

In [146]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['labels'] = le.fit_transform(data['labels'])

In [147]:
data['labels'].value_counts()

3    1924
0    1923
1    1923
2    1923
5    1922
4    1895
6     652
Name: labels, dtype: int64

In [148]:
sampling_rate = 20000

In [149]:
import numpy as np
testsamples = int(0.05*len(data))
random_indices = np.random.choice(len(data), testsamples, replace=False)
train = data.drop(random_indices)
test = data.iloc[random_indices]

In [150]:
train.sample(7)

paths  labels
1496     /content/Data/Angry/1047_WSI_ANG_XX.wav       0
10444      /content/Data/Sad/1023_IOM_SAD_XX.wav       5
1352     /content/Data/Angry/1078_ITS_ANG_XX.wav       0
8260   /content/Data/Neutral/1002_TSI_NEU_XX.wav       4
2829   /content/Data/Disgust/YAF_mop_disgust.wav       1
12156     /content/Data/Surprised/YAF_jug_ps.wav       6
1635      /content/Data/Angry/YAF_burn_angry.wav       0

In [151]:
train.shape

(11554, 2)

In [152]:
test.sample(7)

paths  labels
5070             /content/Data/Fear/1075_WSI_FEA_XX.wav       2
11700               /content/Data/Surprised/DC_su09.wav       6
11572  /content/Data/Surprised/03-01-08-02-02-01-14.wav       6
5540               /content/Data/Fear/YAF_long_fear.wav       2
3296          /content/Data/Disgust/1042_IOM_DIS_XX.wav       1
8               /content/Data/Angry/1081_DFA_ANG_XX.wav       0
861             /content/Data/Angry/1044_TSI_ANG_XX.wav       0

In [153]:
test.shape

(608, 2)

In [154]:
import librosa

In [155]:
# def extract_mfcc(filename):
#     y, sr = librosa.load(filename, duration=3, offset=0.5)
#     mfcc = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40).T, axis=0)
#     return mfcc

In [156]:
# trainx = train['paths'].apply(lambda x: extract_mfcc(x))

In [157]:
# testx = test['paths'].apply(lambda x: extract_mfcc(x))

In [158]:
# trainx = [x for x in trainx]
# trainx = np.array(trainx)
# trainx.shape

(11554, 40)

In [159]:
# testx = [x for x in testx]
# testx = np.array(testx)
# testx.shape

(608, 40)

In [160]:
# trainx = np.expand_dims(trainx, -1)
# trainx.shape

(11554, 40, 1)

In [161]:
# testx = np.expand_dims(testx, -1)
# testx.shape

(608, 40, 1)

In [162]:
# trainy = pd.get_dummies(train['labels'])
# # testy = pd.get_dummies(test['labels'])

In [163]:
# trainy.shape, testy.shape

((11554, 7), (608, 7))

In [164]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from keras.models import Model
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D #, AveragePooling1D
from keras.layers import Flatten, Dropout, Activation # Input,
from keras.layers import Dense , Embedding

In [173]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(40, 1)))
model.add(layers.BatchNormalization())
model.add(layers.Conv1D(128, kernel_size=3, activation='relu'))
model.add(layers.MaxPooling1D(pool_size=2))
model.add(layers.BatchNormalization())
model.add(layers.Bidirectional(layers.LSTM(128, return_sequences=True)))
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.BatchNormalization())
model.add(layers.Dropout(0.2))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(7, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 38, 64)            256       
                                                                 
 batch_normalization (Batch  (None, 38, 64)            256       
 Normalization)                                                  
                                                                 
 conv1d_1 (Conv1D)           (None, 36, 128)           24704     
                                                                 
 max_pooling1d (MaxPooling1  (None, 18, 128)           0         
 D)                                                              
                                                                 
 batch_normalization_1 (Bat  (None, 18, 128)           512       
 chNormalization)                                                
                                                      

In [175]:
# training_model = model.fit(trainx, trainy, validation_split=0.2, epochs=400, batch_size=64)

Epoch 1/400
145/145 [==============================] - 2s 16ms/step - loss: 0.0240 - accuracy: 0.9913 - val_loss: 19.2753 - val_accuracy: 0.1484
Epoch 2/400
145/145 [==============================] - 3s 18ms/step - loss: 0.0244 - accuracy: 0.9913 - val_loss: 20.7077 - val_accuracy: 0.1398
Epoch 3/400
145/145 [==============================] - 2s 11ms/step - loss: 0.0188 - accuracy: 0.9931 - val_loss: 19.4746 - val_accuracy: 0.1393
Epoch 4/400
145/145 [==============================] - 2s 11ms/step - loss: 0.0151 - accuracy: 0.9945 - val_loss: 21.1013 - val_accuracy: 0.1186
Epoch 5/400
145/145 [==============================] - 2s 11ms/step - loss: 0.0125 - accuracy: 0.9961 - val_loss: 19.4369 - val_accuracy: 0.1354
Epoch 6/400
145/145 [==============================] - 2s 11ms/step - loss: 0.0125 - accuracy: 0.9959 - val_loss: 19.0676 - val_accuracy: 0.1545
Epoch 7/400
145/145 [==============================] - 2s 11ms/step - loss: 0.0128 - accuracy: 0.9961 - val_loss: 18.0523 - val_ac

In [176]:
# model_name = 'Speech_Emotion_Recognition_Model1.h5'
# save_dir = os.path.join(os.getcwd(), 'Trained_Models')
# # Save model and weights
# if not os.path.isdir(save_dir):
#     os.makedirs(save_dir)
# model_path = os.path.join(save_dir, model_name)
# model.save(model_path)
# print('Saved trained model at %s ' % model_path)

Saved trained model at /content/Trained_Models/Speech_Emotion_Recognition_Model1.h5 


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [177]:
# preds = model.predict(testx, batch_size=64, verbose=1)

10/10 [==============================] - 1s 9ms/step


In [178]:
# preds=preds.argmax(axis=1)

In [180]:
# abc = preds.astype(int).flatten()

In [182]:
# predictions = (le.inverse_transform((abc)))

In [186]:
# preddf = pd.DataFrame()

In [187]:
# preddf['predicted'] = predictions

In [202]:
# actual=testy.values.argmax(axis=1)
# abc123 = actual.astype(int).flatten()
# # actualvalues = (le.inverse_transform((abc123)))

In [203]:
# acc_report(predictions, actualvalues)

the accuracy of tha model is  0.5049342105263158
[[70  9  9 14  9  3 11]
 [ 4 54 18 11  9 29  6]
 [ 3 13 55 16  3 27  6]
 [ 5  5 11 54 12  1  8]
 [ 2 18  6  6 55 22  1]
 [ 0  2  0  0  2 19  0]
 [ 0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

       Angry       0.83      0.56      0.67       125
     Disgust       0.53      0.41      0.47       131
        Fear       0.56      0.45      0.50       123
       Happy       0.53      0.56      0.55        96
     Neutral       0.61      0.50      0.55       110
         Sad       0.19      0.83      0.31        23
   Surprised       0.00      0.00      0.00         0

    accuracy                           0.50       608
   macro avg       0.47      0.47      0.43       608
weighted avg       0.60      0.50      0.54       608



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
